#ifndef SOCKET_RUNTIME_WEBASSEMBLY_BITS_LIMITS_H
#define SOCKET_RUNTIME_WEBASSEMBLY_BITS_LIMITS_H

#define PAGE_SIZE 4096
#define LONG_BIT 32
#define LONG_MAX 0x7fffffffL
#define LLONG_MAX 0x7fffffffffffffffLL

#endif
