name: Node CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 8

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: npm test
      run: |
        npm i
        npm test
