name: Tests

on: [push]

jobs:
  socket-api-tests:
    uses: socketsupply/socket-api-tests-workflow/.github/workflows/tests.yml@main
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      PACKAGE_PAT: ${{ secrets.PACKAGE_PAT }}
    with:
      skip_git_clone_socket_api: true
